name: Deploy (Firebase Hosting)

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (web)
        working-directory: web
        run: npm ci

      - name: Build (web)
        working-directory: web
        run: npm run build

      # ===== PROD =====
      - name: Deploy PROD (live)
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SA_PROD }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID_PROD }}
          channelId: live

      # ===== DEV =====
      - name: Deploy DEV
        if: github.ref == 'refs/heads/dev'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SA_DEV }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          channelId: dev
          expires: 30d